[[instances]]
name = "slashdot"
nick = "slashdot"
ircname = "Slashdot - http://slashdot.org/, SoylentNews"
channel = "#news.cz,#linux.cz"
refresh_minutes = 30
opml_path = "feeds/slashdot.opml"
extract_url = false
multisource = false

[[instances]]
name = "newscz"
nick = "newscz"
ircname = "See https://pasky.or.cz/rss.txt for list of feeds"
channel = "#news.cz"
refresh_minutes = 10
opml_path = "feeds/newscz.opml"
extract_url = true
multisource = true

[[instances]]
name = "longreads"
nick = "longreads"
ircname = "RSS feeds Petra Koubskeho + HN top 2025"
channel = "#news.cz"
refresh_minutes = 30
opml_path = "feeds/longreads.opml"
extract_url = true
multisource = true
